baseURL = "mahesh-hegde.github.io"
languageCode = "en-us"
title = "Mahesh's Blog"
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3

[params]
mode="toggle"
useCDN=true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mahesh-hegde"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/never_inline/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/mahesh-bhaskar-hegde"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

