baseURL = "https://mahesh-hegde.github.io/"
languageCode = "en"
title = "Loop Invariant"
theme = "gokarna"

# Code Highlight

[params]
	showPostsOnHomePage = "recent"
	enableRobotsTXT = true
  footer = "Mahesh Hegde"

[menu]

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book-open'></span>"
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # Display name
    name = "Posts"
    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "CV"
    name = "CV"
    url = "/cv/"
    weight = 3
    pre = "<span data-feather='briefcase'></span>"

  [[menu.main]]
    identifier = "Readings"
    name = "Readings"
    url = "/readings/"
    pre = "<span data-feather='book'></span>"
    weight = 4

  [[menu.main]]
    identifier = "email"
    url = "mailto:net.mahesh29@gmail.com"
    pre = "<span data-feather='mail'></span>"
    weight = 6
 
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/mahesh-hegde"
    weight = 6
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/mahesh-bhaskar-hegde/"
    weight = 7
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='linkedin'></span>"
